import { Inter } from 'next/font/google';
import './globals.css';


import { getServerSession } from 'next-auth';



import AuthProviders from '@/providers/AuthProviders';
import Navbar from '@/common/Navbar';
import ThemeProviders from '@/providers/ThemeProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Home | News24',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProviders session={session}>
          <ThemeProviders
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            <Navbar />
            {children}

          </ThemeProviders>
        </AuthProviders>
      </body>
    </html>
  );
}
